import { accessSync, constants, statSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";

// This entrypoint is for the production container. Never start with a writable
// but disposable container database after a missing or misconfigured mount.
const databasePath = process.env.TRAVEL_DATABASE_PATH;
if (!databasePath || !isAbsolute(databasePath) || dirname(resolve(databasePath)) !== "/data") {
  throw new Error("TRAVEL_DATABASE_PATH must point to a database file directly inside /data.");
}

try {
  if (!statSync("/data/.travel-persistent-storage").isFile()) {
    throw new Error("Storage marker is not a file.");
  }
  accessSync("/data", constants.R_OK | constants.W_OK | constants.X_OK);
} catch (cause) {
  throw new Error(
    "Persistent travel storage is not ready. Mount a writable /data directory with the .travel-persistent-storage marker; see docs/DEPLOYMENT.md.",
    { cause },
  );
}

// Use the Next.js standalone server generated by the build.
await import("../server.js");
